name:                AdventOfCode2024
version:             0.1.0.0
github:              "githubuser/AdventOfCode2024"
license:             BSD3
author:              "Raphael Colman"
maintainer:          "example@example.com"
copyright:           "2022 Raphael Colman"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/AdventOfCode2024#readme>

dependencies:
- base >= 4.7 && < 5
- advent-of-code-api >= 0.2.8
- text
- dotenv
- transformers
- trifecta
- directory
- text-format
- containers
- combinatorial
- linear
- lens
- split
- mtl
- safe 
- finite-typelits
- monad-loops
- monad-extras
- PSQueue
- parser-combinators
- parsers
- regex-tdfa
- search-algorithms
- timeit >= 2.0

library:
  source-dirs: src

executables:
  AdventOfCode2024-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AdventOfCode2024

tests:
  AdventOfCode2024-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AdventOfCode2024
